# Site wide configuration

title: Generally Biology
description: A blog about the intersection of computer science and biology
logo: dnaimage.jpg # 120x120 px default image used for Twitter summary card teaser: skinny-bones-demo.gif locale: en
url: http://generallybiology.com/
feed:
  path: atom.xml

header:
        image: "Plants.jpg"
        homepage-image: "Plants.jpg"
# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/

kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


breadcrumbs: true
breadcrumb_home_label : "Blog"
breadcrumb_separator  : ">"



# Site owner
owner: jome0169
name: Pablo-Mendieta
email: John.mendieta@uga.edu
twitter: pabster212
google:
  ad-client:
  ad-slot:
bio: A computational biologist interested in those little green things that stick out of the ground everywhere
avatar: "/images/Pablo_small.jpg" # 160x160 px image for author byline
disqus-shortname:



defaults:
  # _pages
  - scope:
      path: ""
      type: default
    values:
      layout: single
      author_profile: true


#
#post Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

#Archive Settings


permalinmlink: /:categories/:title/
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/


exclude:
  - vendor 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
