# Site wide configuration

title: Generally Biology
description: A blog about computer science, biology, and everything else
logo: dnaimage.jpg # 120x120 px default image used for Twitter summary card
teaser: skinny-bones-demo.gif
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/

kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


breadcrumbs: true
breadcrumb_home_label : "home"
breadcrumb_separator  : ">"



# Site owner
owner: jome0169
name: Pablo-Mendieta
email: John.mendieta@colorado.edu
twitter: pabster212
google:
  ad-client:
  ad-slot:
bio: A computational interested in those little green things that stick out of the ground everywhere
avatar: /images/dnaimage.jpg # 160x160 px image for author byline
disqus-shortname:




#post Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

#Archive Settings
#

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/



exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
